import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import s_frases from '@/styles/Frases.module.css'
import s_chat from '@/styles/Chat.module.css'
import styles from '@/styles/Home.module.css'
import { use, useEffect, useState } from 'react'
const inter = Inter({ subsets: ['latin'] })
let pp_Norris = "https://wl-genial.cf.tsp.li/resize/728x/jpg/225/701/6612535fd88221c934e7819be8.jpg"

export default function Home() {

	const data = 
	{
		"frases": [
			{
				"imagen": "images/chucktellamaaltelefono.jpg",
				"frase": "Si te llama chuck norris, tienes dos opciones, contestar o contestar",
				"id": "1",
				"idioma": "español",
				"categoria": "tecnologia"
			},
			{
				"imagen": "images/experienciacercanamuerte.jpg",
				"frase": "En una ocasion la muerte tuvo una experiencia cercana a chuck norris",
				"id": "2",
				"idioma": "español",
				"categoria": "salud"
			},
			{
				"imagen": "images/infartossobrevivieronachuck.jpeg",
				"frase": "Chuck norris no sobrevivió a dos infartos, los infartos sobrevivieron a chuck norris",
				"id": "3",
				"idioma": "español",
				"categoria": "salud"
			},
			{
				"imagen": "images/lagrimascurancancer.jpg",
				"frase": "Sus lagrimas curan el cancer. Es una pena que el no ha llorado nunca",
				"id": "4",
				"idioma": "español",
				"categoria": "salud"
			},
			{
				"imagen": "images/martillodethor.jpg",
				"frase": "Thor sacó su martillo, de la caja de herramientas de chuck norris",
				"id": "5",
				"idioma": "español",
				"categoria": "comics"
			},
			{
				"imagen": "images/noleelibros.jpg",
				"frase": "Chuck Norris no lee libros. Los mira fijamente hasta que consigue la informacion que quiere...",
				"id": "6",
				"idioma": "español",
				"categoria": "lectura"
			},
			{
				"imagen": "images/nuncaafoteesachuck.png",
				"frase": "Cuando chuck norris nació... la unica persona que lloró fue el doctor. Nunca afotees a chuck ",
				"id": "7",
				"idioma": "español",
				"categoria": "salud"
			},
			{
				"imagen": "images/pokemonGo.webp",
				"frase": "Chuck norris ya ha capturado todos los pokemons... desde un telefono fijo",
				"id": "8",
				"idioma": "español",
				"categoria": "tecnologia"
			},
			{
				"imagen": "images/serieporultimavez.png",
				"frase": "El que rie ultimo, rie mejor. Pero aquel que se rie de chuck, se rie por ultima vez.",
				"id": "9",
				"idioma": "español",
				"categoria": "humor"
			},
			{
				"imagen": "images/teoriadeevolucion.png",
				"frase": "No hay teoria de la evolucion. Solo una lista de criaturas que chuck deja vivir",
				"id": "10",
				"idioma": "español",
				"categoria": "biologia"
			},
			{
				"imagen": "images/tequedan7dias.jpg",
				"frase": "La chica del aro llama a chuck norris y chuck le avisa que le quedan 7 dias",
				"id": "11",
				"idioma": "español",
				"categoria": "horror"
			}
		]
	}
	const [share, setShare] = useState('');
	const handleClick = (e: any) => {
		let frase = e.target.value;
		if (frase && frase.length > 0) 
		{
			let formattedQuery = frase.replaceAll(" ", "%20");
			setShare(formattedQuery);
		}
	}
	useEffect(() => {

		const openTwitterIntent = () => {
			if(share)
			{
				window.open('https://twitter.com/intent/tweet?text=' + share, '_blank')
			}
		}

		openTwitterIntent();
	}, [share]);


	const [messages, setMessages]: any = useState([]);
	const [text, setText] = useState('');

	const handleSubmit = (e:any) => {
		handleSubmitUserMessage(text);
		setText('');
	}

	const handleSubmitUserMessage = (text:any) => {
		const newMessage = { text, sender: 'user'};
		setMessages([...messages, newMessage]);

		setTimeout(() => {
			const chuckAnswer = { text: generateChuckAnswer(), sender: 'chuck'}
			setMessages([...messages, chuckAnswer]);
		}, 500);

		const generateChuckAnswer = () => {
			//...
		}
	}

	console.log(messages)

	return (
		<>
			<div>
				<div className={`${s_chat.chat_container}`}>
					<div className={`${s_chat.chat}`}>
						{messages.map((message: any, i:any) => (
							<div key={i}>
								<p>{message.text}</p>
							</div>
						))}
					</div>
				</div>
				<form onSubmit={handleSubmit}>
					<input type="text" value={text} onChange={((e) => setText(e.target.value))} placeholder='Chuck, I need help with a T-shirt purchase...'/>
					<button type='submit'>Ask</button>
				</form>
			</div>

			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${styles.main} ${inter.className}`}>
				<div className={`${s_frases.container}`}>
						<div className={`${s_frases.inner_container}`}>
							<Image src={pp_Norris} width={40} height={40} alt="Chuck Norris" className={`${s_frases.chuck_pp_image}`}/>
							<p onClick={handleClick} className={`${s_frases.frase} ${s_frases.welcome_frase}`}><span>Welcome to Chuck Norris support zone!</span> Get ready for a ride where problems dont stand a chance! Chucks here to obliterate issues <span>faster than his roundhouse kicks!</span> Brace yourself for solutions served with a side of unstoppable awesomeness! <span>Welcome to the support zone where Chuck Norris reigns supreme!</span></p>
						</div>
					{
						
						data.frases.map((frase) => {
							return (
								<div key={frase.id} className={`${s_frases.inner_container}`}>
									<Image src={pp_Norris} width={40} height={40} alt="Chuck Norris" className={`${s_frases.chuck_pp_image}`}/>
									<div className={`${s_frases.message}`}>
										<p key={frase.id} className={`${s_frases.frase}`}>{frase.frase}</p>
										<button className={`${s_frases.share_button}`} onClick={handleClick} value={frase.frase}>Share</button>
									</div>
								</div>
							)
						})
					}
				</div>
			</main>
		</>
	)
}
